export const catalogoPPC = [
  // --- CURSO INTEGRADO ---
  { nome: 'Língua Portuguesa I', chAula: 80, curso: 'Integrado' }, { nome: 'Língua Inglesa I', chAula: 80, curso: 'Integrado' }, { nome: 'Redação', chAula: 80, curso: 'Integrado' }, { nome: 'Educação Física I', chAula: 40, curso: 'Integrado' }, { nome: 'Artes', chAula: 40, curso: 'Integrado' }, { nome: 'Matemática I', chAula: 160, curso: 'Integrado' }, { nome: 'Física I', chAula: 120, curso: 'Integrado' }, { nome: 'Química I', chAula: 120, curso: 'Integrado' }, { nome: 'Sociologia I', chAula: 80, curso: 'Integrado' }, { nome: 'Filosofia I', chAula: 80, curso: 'Integrado' }, { nome: 'História I', chAula: 80, curso: 'Integrado' }, { nome: 'Geografia I', chAula: 120, curso: 'Integrado' }, { nome: 'Biologia I', chAula: 120, curso: 'Integrado' }, { nome: 'Informática Básica e Aplicada', chAula: 80, curso: 'Integrado' }, { nome: 'Circuitos Elétricos', chAula: 200, curso: 'Integrado' }, { nome: 'Eletricidade', chAula: 120, curso: 'Integrado' },
  { nome: 'Língua Portuguesa II', chAula: 120, curso: 'Integrado' }, { nome: 'Língua Inglesa II', chAula: 80, curso: 'Integrado' }, { nome: 'Educação Física II', chAula: 40, curso: 'Integrado' }, { nome: 'Matemática II', chAula: 120, curso: 'Integrado' }, { nome: 'Física II', chAula: 160, curso: 'Integrado' }, { nome: 'Química II', chAula: 120, curso: 'Integrado' }, { nome: 'Sociologia II', chAula: 80, curso: 'Integrado' }, { nome: 'Filosofia II', chAula: 80, curso: 'Integrado' }, { nome: 'História II', chAula: 120, curso: 'Integrado' }, { nome: 'Geografia II', chAula: 80, curso: 'Integrado' }, { nome: 'Biologia II', chAula: 120, curso: 'Integrado' }, { nome: 'Dispositivos Eletrônicos', chAula: 160, curso: 'Integrado' }, { nome: 'Laboratório de Dispositivos Eletrônicos', chAula: 80, curso: 'Integrado' }, { nome: 'Técnicas Digitais', chAula: 120, curso: 'Integrado' }, { nome: 'Laboratório de Técnicas Digitais', chAula: 80, curso: 'Integrado' },
  { nome: 'Língua Portuguesa III', chAula: 80, curso: 'Integrado' }, { nome: 'Língua Inglesa III', chAula: 80, curso: 'Integrado' }, { nome: 'Educação Física III', chAula: 40, curso: 'Integrado' }, { nome: 'Matemática III', chAula: 120, curso: 'Integrado' }, { nome: 'Sociologia III', chAula: 40, curso: 'Integrado' }, { nome: 'Filosofia III', chAula: 40, curso: 'Integrado' }, { nome: 'Saúde, Meio Ambiente e Segurança no Trabalho', chAula: 80, curso: 'Integrado' }, { nome: 'Redes de Computadores', chAula: 80, curso: 'Integrado' }, { nome: 'Infraestrutura de Hardware e Software', chAula: 80, curso: 'Integrado' }, { nome: 'Linguagem de Programação', chAula: 120, curso: 'Integrado' }, { nome: 'Sistemas Programáveis', chAula: 120, curso: 'Integrado' }, { nome: 'Sistemas Digitais', chAula: 120, curso: 'Integrado' }, { nome: 'Sistemas de Automação', chAula: 160, curso: 'Integrado' }, { nome: 'Telecomunicações', chAula: 120, curso: 'Integrado' }, { nome: 'Artes (3º Ano)', chAula: 80, curso: 'Integrado' }, { nome: 'Língua Espanhola', chAula: 80, curso: 'Integrado' }, { nome: 'Eletrônica de Potência', chAula: 80, curso: 'Integrado' },
  
  // --- CURSO SUBSEQUENTE ---
  { nome: 'Física Aplicada', chAula: 72, curso: 'Subsequente' }, { nome: 'Tecnologia dos Materiais', chAula: 36, curso: 'Subsequente' }, { nome: 'Noções Práticas de Eletrônica', chAula: 72, curso: 'Subsequente' }, { nome: 'Informática Aplicada', chAula: 72, curso: 'Subsequente' }, { nome: 'Circuitos Elétricos I', chAula: 72, curso: 'Subsequente' }, { nome: 'Inglês Técnico', chAula: 36, curso: 'Subsequente' },
  { nome: 'Circuitos Elétricos II', chAula: 108, curso: 'Subsequente' }, { nome: 'Segurança, Meio Ambiente e Saúde', chAula: 36, curso: 'Subsequente' }, { nome: 'Eletrônica Digital I', chAula: 72, curso: 'Subsequente' }, { nome: 'Atuadores Elétricos', chAula: 36, curso: 'Subsequente' }, { nome: 'Eletrônica Analógica', chAula: 108, curso: 'Subsequente' },
  { nome: 'Eletrônica Digital II', chAula: 108, curso: 'Subsequente' }, { nome: 'Organizações, Normas e Qualidade', chAula: 36, curso: 'Subsequente' }, { nome: 'Princípios de Telecomunicações', chAula: 72, curso: 'Subsequente' }, { nome: 'Redes de Computadores', chAula: 36, curso: 'Subsequente' }, { nome: 'Eletrônica Aplicada', chAula: 108, curso: 'Subsequente' },
  { nome: 'Sistemas Programáveis (Subsequente)', chAula: 108, curso: 'Subsequente' }, { nome: 'Eletrônica de Potência (Subsequente)', chAula: 36, curso: 'Subsequente' }, { nome: 'Sistemas de Telecomunicações', chAula: 72, curso: 'Subsequente' }, { nome: 'Instalações Prediais', chAula: 36, curso: 'Subsequente' }, { nome: 'Princípios de Automação e Instrumentação', chAula: 108, curso: 'Subsequente' }
];
